export const userData = [
  {
    name: "Dejon Fay",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Baby",
    username: "@dejonfay",
    rating: "2321",
    country: "United Kingdom",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/GB.svg",
    profession: "Frontend Develeoper",
    problemsSolved: 430,
    solutionsSubmittes: 680,
  },
  {
    name: "Bart Jast",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Bandit",
    username: "@bartjast",
    rating: "1298",
    country: "United States",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/US.svg",
    profession: "Software Engineer",
    problemsSolved: 540,
    solutionsSubmittes: 780,
  },
  {
    name: "Ida West",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Jasper",
    username: "@idavest",
    rating: "8978",
    country: "United States",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/US.svg",
    profession: "Business Analyst",
    problemsSolved: 480,
    solutionsSubmittes: 1200,
  },
  {
    name: "Gino Wolf",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Leo",
    username: "@ginowolf",
    rating: "980459",
    country: "South Korea",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/KR.svg",
    profession: "Software Engineer",
    problemsSolved: 680,
    solutionsSubmittes: 980,
  },
  {
    name: "Chad Yost",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Bella",
    username: "@chadyost",
    rating: "356863",
    country: "Japan",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/JP.svg",
    profession: "Backend Developer",
    problemsSolved: 980,
    solutionsSubmittes: 1358,
  },
  {
    name: "Dejon Fay",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Baby",
    username: "@dejonfay",
    rating: "2321",
    country: "United Kingdom",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/GB.svg",
    profession: "Frontend Develeoper",
    problemsSolved: 430,
    solutionsSubmittes: 680,
  },
  {
    name: "Bart Jast",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Bandit",
    username: "@bartjast",
    rating: "1298",
    country: "United States",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/US.svg",
    profession: "Software Engineer",
    problemsSolved: 540,
    solutionsSubmittes: 780,
  },
  {
    name: "Ida West",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Jasper",
    username: "@idavest",
    rating: "8978",
    country: "United States",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/US.svg",
    profession: "Business Analyst",
    problemsSolved: 480,
    solutionsSubmittes: 1200,
  },
  {
    name: "Gino Wolf",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Leo",
    username: "@ginowolf",
    rating: "980459",
    country: "South Korea",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/KR.svg",
    profession: "Software Engineer",
    problemsSolved: 680,
    solutionsSubmittes: 980,
  },
  {
    name: "Chad Yost",
    profilePicture: "https://api.dicebear.com/6.x/bottts/svg?seed=Bella",
    username: "@chadyost",
    rating: "356863",
    country: "Japan",
    countryFlag:
      "https://static-fastly.hackerearth.com/static/hackerearth/images/flags/JP.svg",
    profession: "Backend Developer",
    problemsSolved: 980,
    solutionsSubmittes: 1358,
  }
];
